################################################################################
# Automatically-generated file. Do not edit!
################################################################################

BBL_SRCS_QUOTED := 
S_SRCS_OS_FORMAT := 
ASM_UPPER_SRCS_QUOTED := 
OBJ_SRCS := 
ABS_SRCS_QUOTED := 
BBL_SRCS := 
ASM_SRCS := 
OBJ_SRCS_OS_FORMAT := 
ASM_UPPER_SRCS := 
BBL_SRCS_OS_FORMAT := 
ASM_SRCS_OS_FORMAT := 
ABS_SRCS := 
TODISASSEMBLE_SRCS_OS_FORMAT := 
S_UPPER_SRCS_QUOTED := 
ABS_SRCS_OS_FORMAT := 
TODISASSEMBLE_SRCS := 
S_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS_QUOTED := 
ASM_SRCS_QUOTED := 
S_SRCS_QUOTED := 
ASM_UPPER_SRCS_OS_FORMAT := 
TODISASSEMBLE_SRCS_QUOTED := 
S_UPPER_SRCS_OS_FORMAT := 
S_DEPS_QUOTED := 
ASM_DEPS_OS_FORMAT := 
BURNER_OUTPUT_OUTPUTS := 
OBJS := 
S_UPPER_DEPS_OS_FORMAT := 
ASM_DEPS_QUOTED := 
EXECUTABLES_OS_FORMAT := 
BURNER_OUTPUT_OUTPUTS_QUOTED := 
S_DEPS := 
S_DEPS_OS_FORMAT := 
S_UPPER_DEPS := 
ASM_UPPER_DEPS_QUOTED := 
ASM_DEPS := 
ASM_UPPER_DEPS := 
OBJS_QUOTED := 
BURNER_OUTPUT_OUTPUTS_OS_FORMAT := 
ASM_UPPER_DEPS_OS_FORMAT := 
EXECUTABLES_QUOTED := 
S_UPPER_DEPS_QUOTED := 
EXECUTABLES := 
OBJS_OS_FORMAT := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Sources \
Project_Settings/Linker_Files \

